definitions:
  model.ProjectPermit:
    properties:
      project_id:
        type: integer
      project_name:
        type: string
      project_role:
        type: integer
    type: object
  model.UserResponse:
    properties:
      avatar:
        type: string
      name:
        type: string
      project_permit:
        items:
          $ref: '#/definitions/model.ProjectPermit'
        type: array
      role:
        type: integer
      user_id:
        type: integer
    type: object
  request.AuditReq:
    properties:
      item_id:
        type: integer
      project_id:
        type: integer
      reason:
        type: string
      status:
        type: integer
    type: object
  request.CreateProject:
    properties:
      audio_rule:
        type: string
      logo:
        type: string
      name:
        type: string
      user_ids:
        items:
          type: integer
        type: array
    type: object
  request.DeleteProject:
    properties:
      project_id:
        type: integer
    type: object
  request.GetUserReq:
    properties:
      project_id:
        type: integer
      role:
        type: integer
    type: object
  request.LoginReq:
    properties:
      code:
        type: string
    type: object
  request.SelectReq:
    properties:
      auditor:
        type: string
      page:
        type: integer
      page_size:
        type: integer
      project_id:
        type: integer
      query:
        type: string
      status:
        type: string
      tag:
        description: RoundTime [][]int  `json:"round_time"`
        type: string
    type: object
  request.UpdateUserReq:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
  request.UpdateUserRoleReq:
    properties:
      project_permit:
        items:
          $ref: '#/definitions/model.ProjectPermit'
        type: array
      role:
        type: integer
      user_id:
        type: integer
    type: object
  request.UploadReq:
    properties:
      api_key:
        type: string
      auditor:
        type: string
      author:
        type: string
      content:
        $ref: '#/definitions/response.Contents'
      extra: {}
      hook_url:
        type: string
      id:
        type: integer
      public_time:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  response.Comment:
    properties:
      content:
        type: string
      pictures:
        items:
          type: string
        type: array
    type: object
  response.Contents:
    properties:
      last_comment:
        $ref: '#/definitions/response.Comment'
      next_comment:
        $ref: '#/definitions/response.Comment'
      topic:
        $ref: '#/definitions/response.Topics'
    type: object
  response.GetDetailResp:
    properties:
      api_key:
        type: string
      audit_rule:
        type: string
      current_number:
        type: integer
      members:
        items:
          $ref: '#/definitions/model.UserResponse'
        type: array
      totle_number:
        type: integer
    type: object
  response.Item:
    properties:
      auditor:
        type: string
      author:
        type: string
      content:
        $ref: '#/definitions/response.Contents'
      item_id:
        type: integer
      public_time:
        type: string
      status:
        type: integer
      tags:
        items:
          type: string
        type: array
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.SelectResp:
    properties:
      items:
        items:
          $ref: '#/definitions/response.Item'
        type: array
      project_id:
        type: integer
    type: object
  response.Topics:
    properties:
      content:
        type: string
      pictures:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  response.UserInfo:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
      role:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/item/audit:
    post:
      consumes:
      - application/json
      description: 审核项目并更新审核状态
      parameters:
      - description: 审核请求体
        in: body
        name: auditReq
        required: true
        schema:
          $ref: '#/definitions/request.AuditReq'
      produces:
      - application/json
      responses:
        "200":
          description: 审核成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 审核失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Item
  /api/v1/item/searchHistory:
    get:
      consumes:
      - application/json
      description: 获取用户的历史记录（审核历史）
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回历史记录
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.Item'
                  type: array
              type: object
        "400":
          description: 获取历史记录失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Item
  /api/v1/item/select:
    post:
      consumes:
      - application/json
      description: 根据请求的条件获取项目和相关项目信息
      parameters:
      - description: 查询条件
        in: body
        name: selectReq
        required: true
        schema:
          $ref: '#/definitions/request.SelectReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回项目列表
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.SelectResp'
                  type: array
              type: object
        "400":
          description: 查询失败
          schema:
            $ref: '#/definitions/response.Response'
      tags:
      - Item
  /api/v1/item/upload:
    post:
      consumes:
      - application/json
      description: 上传新的项目或文件
      parameters:
      - description: 上传请求体
        in: body
        name: uploadReq
        required: true
        schema:
          $ref: '#/definitions/request.UploadReq'
      produces:
      - application/json
      responses:
        "200":
          description: 上传成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 上传失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Item
  /api/v1/project/create:
    post:
      consumes:
      - application/json
      description: 根据请求体参数创建新的项目
      parameters:
      - description: 创建项目请求体
        in: body
        name: createProject
        required: true
        schema:
          $ref: '#/definitions/request.CreateProject'
      produces:
      - application/json
      responses:
        "200":
          description: 项目创建成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 无权限或创建失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Project
  /api/v1/project/delete:
    delete:
      consumes:
      - application/json
      description: 通过项目 ID 删除指定的项目
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 删除项目请求参数
        in: body
        name: delete
        required: true
        schema:
          $ref: '#/definitions/request.DeleteProject'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 删除失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除项目
      tags:
      - Project
  /api/v1/project/detail:
    get:
      consumes:
      - application/json
      description: 根据项目 ID 获取项目的详细信息
      parameters:
      - description: 项目ID
        in: query
        name: projectId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取项目详细信息成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetDetailResp'
              type: object
        "400":
          description: 获取项目详细信息失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Project
  /api/v1/project/getProjectList:
    get:
      consumes:
      - application/json
      description: 获取所有项目列表，根据 logo 过滤
      parameters:
      - description: Logo过滤字段
        in: header
        name: X-Header-Param
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回项目列表
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 获取项目列表失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Project
  /api/v1/user/GetMyInfo:
    get:
      consumes:
      - application/json
      description: 获取用户名，邮箱，权限
      produces:
      - application/json
      responses:
        "200":
          description: 获取信息成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserInfo'
              type: object
        "400":
          description: 失败
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Auth
  /api/v1/user/GetQiToken:
    get:
      consumes:
      - application/json
      description: 获取用于上传文件的七牛云 Token
      produces:
      - application/json
      responses:
        "200":
          description: 返回上传 Token
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 获取图床token失败
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Auth
  /api/v1/user/getUsers:
    post:
      consumes:
      - application/json
      description: 根据项目 ID 获取用户列表，要求角色为 2 才有权限
      parameters:
      - description: 获取用户请求体
        in: body
        name: GetUserReq
        required: true
        schema:
          $ref: '#/definitions/request.GetUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功获取用户列表
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.UserResponse'
                  type: array
              type: object
        "400":
          description: 获取失败
          schema:
            $ref: '#/definitions/response.Response'
        "40001":
          description: 无权限
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - User
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 通过邮箱登录，返回用户的 Token
      parameters:
      - description: 登录请求体
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/request.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回Token
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: 错误信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
        "20001":
          description: 审核中
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
      tags:
      - Auth
  /api/v1/user/logout:
    post:
      consumes:
      - application/json
      description: 清除用户 Token
      produces:
      - application/json
      responses:
        "200":
          description: 成功登出
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Auth
  /api/v1/user/updateMyInfo:
    post:
      consumes:
      - application/json
      description: 更新当前用户的信息，如邮箱、名称和头像
      parameters:
      - description: 更新用户信息请求体
        in: body
        name: update
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功更新用户信息
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Auth
  /api/v1/user/updateUser:
    post:
      consumes:
      - application/json
      description: 修改指定用户的角色，根据项目权限设置角色信息
      parameters:
      - description: 更新用户角色请求体
        in: body
        name: UpdateUserRoleReq
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserRoleReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功更新用户角色
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 修改失败
          schema:
            $ref: '#/definitions/response.Response'
        "40001":
          description: 无权限
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - User
swagger: "2.0"
